name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # optional: if you want to trigger on version tags too

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Git metadata
        id: vars
        run: |
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          # Optional: only add if it's a tag
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            lewiskinyuanjue/food-project:latest
            lewiskinyuanjue/food-project:${{ steps.vars.outputs.SHA }}
            lewiskinyuanjue/food-project:${{ steps.vars.outputs.BRANCH }}
            ${{ steps.vars.outputs.TAG && format('lewiskinyuanjue/food-project:{0}', steps.vars.outputs.TAG) }}
